baseURL = "http://abarrosjr.github.io/"
languageCode = "pt_BR"
title = "abarrosjr"
theme = "LucentLink-Hugo"
minVersion = "0.115.0"

[params]
  description     = "Developer curious about computer engineering and open source"
  googleAnalytics = "G-BF1DJ9JZF3"

[outputs]
  home = ["HTML"]
