baseURL = "devjunr.github.io"
languageCode = "pt-br"
title = "Adriano Jr"
theme = "LucentLink-Hugo"
minVersion = "0.115.0"

[params]
  description     = "Desenvolvedor de Softwares"
  googleAnalytics = ""    # your GA ID, if any

[outputs]
  home = ["HTML"]
